version: '3.5'

services:
  api:
    build: 
      context: .
      dockerfile: ./docker/containers/api/Dockerfile
    volumes:
      - ./:/go/src/app:cached
    ports: 
      - 8080:8080
    tty: true
    stdin_open: true
    environment:
      DB_NAME: examin
      DB_USERNAME: root
      DB_PASSWORD: ''
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db

  db:
    build:
      context: ./docker/containers/db
    volumes:
      - ./docker/containers/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    ports: 
      - 3316:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'

volumes:
  db_data:
    driver: local
