version: '3.5'

services:
  api:
    build: 
      context: ./docker/containers/api
    volumes:
      - ./:/go/src/app:cached
    ports: 
      - 8080:8080
    tty: true
    stdin_open: true

  db:
    build:
      context: ./docker/containers/db
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - 3316:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"

volumes:
  db_data:
    driver: local
